
name: Deploy Azure Landing Zone - Multi Stage with Generic Action

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  stage-storage:
    name: Stage 1 - Deploy Storage Account
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Storage
        uses: ./.github/actions/terraform-deploy
        with:
          module_target: module.storage

  stage-loganalytics:
    name: Stage 2 - Deploy Log Analytics
    runs-on: ubuntu-latest
    needs: stage-storage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Log Analytics
        uses: ./.github/actions/terraform-deploy
        with:
          module_target: module.loganalytics

  stage-uami:
    name: Stage 3 - Deploy UAMI
    runs-on: ubuntu-latest
    needs: stage-loganalytics
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy UAMI
        uses: ./.github/actions/terraform-deploy
        with:
          module_target: module.uami
