
name: Deploy Azure Landing Zone

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  TF_VERSION: 1.6.0

jobs:
  deploy-storage:
    name: Deploy Storage Account
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init & Plan
        run: |
          cd modules/storage-acc
          terraform init
          terraform plan -out=tfplan

      - name: Terraform Apply
        run: |
          cd modules/storage-acc
          terraform apply -auto-approve tfplan

  deploy-loganalytics:
    name: Deploy Log Analytics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init & Plan
        run: |
          cd modules/log-analytics
          terraform init
          terraform plan -out=tfplan

      - name: Terraform Apply
        run: |
          cd modules/log-analytics
          terraform apply -auto-approve tfplan

  deploy-uami:
    name: Deploy UAMI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init & Plan
        run: |
          cd modules/uami
          terraform init
          terraform plan -out=tfplan

      - name: Terraform Apply
        run: |
          cd modules/uami
          terraform apply -auto-approve tfplan
